"""
Unit tests for the Document Assembly Tool.

These tests use the sample files generated by generate_fixtures.py.
"""

import pytest
import os
import json
import csv
from pathlib import Path
from docx import Document
from src.document_assembler import DocumentAssembler

FIXTURE_DIR = Path(__file__).parent / "fixtures"
SAMPLE_DATA_WORD = FIXTURE_DIR / "sample_data.docx"
SAMPLE_DATA_CSV = FIXTURE_DIR / "sample_data.csv"
SAMPLE_DATA_JSON = FIXTURE_DIR / "sample_data.json"
SAMPLE_TEMPLATE = FIXTURE_DIR / "sample_template.docx"
OUTPUT_TEST = FIXTURE_DIR / "test_output.docx"


@pytest.fixture(scope="module", autouse=True)
def ensure_fixtures():
    """Generate fixtures if missing."""
    if not all(f.exists() for f in [SAMPLE_DATA_WORD, SAMPLE_DATA_CSV, SAMPLE_DATA_JSON, SAMPLE_TEMPLATE]):
        import subprocess
        subprocess.run(["python", str(FIXTURE_DIR.parent / "generate_fixtures.py")], check=True)
    yield


def test_load_data_word():
    assembler = DocumentAssembler(
        data_source=str(SAMPLE_DATA_WORD),
        template_path=str(SAMPLE_TEMPLATE),
        output_path=str(OUTPUT_TEST),
        data_type="word",
        log_level="ERROR"
    )
    data = assembler._load_data_from_word()
    assert "client_name" in data
    assert "project_title" in data
    assert "budget" in data
    # Check that value is list of paragraph dicts
    assert isinstance(data["client_name"], list)
    assert len(data["client_name"]) >= 1
    assert "runs" in data["client_name"][0]


def test_load_data_csv():
    assembler = DocumentAssembler(
        data_source=str(SAMPLE_DATA_CSV),
        template_path=str(SAMPLE_TEMPLATE),
        output_path=str(OUTPUT_TEST),
        data_type="csv",
        log_level="ERROR"
    )
    data = assembler._load_data_from_csv()
    assert "client_name" in data
    assert data["client_name"][0]["runs"][0]["text"] == "Acme Corp"


def test_load_data_json():
    assembler = DocumentAssembler(
        data_source=str(SAMPLE_DATA_JSON),
        template_path=str(SAMPLE_TEMPLATE),
        output_path=str(OUTPUT_TEST),
        data_type="json",
        log_level="ERROR"
    )
    data = assembler._load_data_from_json()
    assert "client_name" in data
    assert data["client_name"][0]["runs"][0]["text"] == "Acme Corp"


def test_find_placeholders():
    assembler = DocumentAssembler(
        data_source=str(SAMPLE_DATA_WORD),
        template_path=str(SAMPLE_TEMPLATE),
        output_path=str(OUTPUT_TEST),
        log_level="ERROR"
    )
    doc = Document(SAMPLE_TEMPLATE)
    placeholders = assembler.find_placeholders(doc)
    # We expect three placeholders: {{client_name}}, {{project_title}}, {{budget}}
    assert len(placeholders) == 3
    field_names = [m.group('field_name') for _, m in placeholders]
    assert set(field_names) == {"client_name", "project_title", "budget"}


def test_insert_data():
    assembler = DocumentAssembler(
        data_source=str(SAMPLE_DATA_WORD),
        template_path=str(SAMPLE_TEMPLATE),
        output_path=str(OUTPUT_TEST),
        data_type="word",
        log_level="ERROR"
    )
    data = assembler.load_data()
    assembler.insert_data(data)
    assert OUTPUT_TEST.exists()
    doc = Document(OUTPUT_TEST)
    full_text = "\n".join([p.text for p in doc.paragraphs])
    # Placeholders should be gone
    assert "{{client_name}}" not in full_text
    assert "{{project_title}}" not in full_text
    assert "{{budget}}" not in full_text
    # Check that data appears
    assert "Acme Corp" in full_text
    assert "Enterprise Platform" in full_text
    assert "$150,000" in full_text

    # Validate that formatting is preserved for inline placeholder replacements.
    bold_runs = [r for p in doc.paragraphs for r in p.runs if r.bold]
    assert any("Acme Corp" in r.text for r in bold_runs)

    # Clean up
    OUTPUT_TEST.unlink(missing_ok=True)
