# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/proto/assembler.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/proto/assembler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19src/proto/assembler.proto\x12\tassembler\"e\n\x0f\x41ssembleRequest\x12\x13\n\x0b\x64\x61ta_source\x18\x01 \x01(\t\x12\x15\n\rtemplate_path\x18\x02 \x01(\t\x12\x13\n\x0boutput_path\x18\x03 \x01(\t\x12\x11\n\tdata_type\x18\x04 \x01(\t\"I\n\x10\x41ssembleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0boutput_path\x18\x03 \x01(\t\"S\n\x0c\x42\x61tchRequest\x12,\n\x08requests\x18\x01 \x03(\x0b\x32\x1a.assembler.AssembleRequest\x12\x15\n\ruse_processes\x18\x02 \x01(\x08\"?\n\rBatchResponse\x12.\n\tresponses\x18\x01 \x03(\x0b\x32\x1b.assembler.AssembleResponse\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x10\n\x0eMetricsRequest\"{\n\x0fMetricsResponse\x12\x38\n\x07metrics\x18\x01 \x03(\x0b\x32\'.assembler.MetricsResponse.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32\xad\x02\n\x11\x44ocumentAssembler\x12K\n\x10\x41ssembleDocument\x12\x1a.assembler.AssembleRequest\x1a\x1b.assembler.AssembleResponse\x12\x42\n\rBatchAssemble\x12\x17.assembler.BatchRequest\x1a\x18.assembler.BatchResponse\x12\x42\n\x0bHealthCheck\x12\x18.assembler.HealthRequest\x1a\x19.assembler.HealthResponse\x12\x43\n\nGetMetrics\x12\x19.assembler.MetricsRequest\x1a\x1a.assembler.MetricsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.assembler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICSRESPONSE_METRICSENTRY']._loaded_options = None
  _globals['_METRICSRESPONSE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_ASSEMBLEREQUEST']._serialized_start=40
  _globals['_ASSEMBLEREQUEST']._serialized_end=141
  _globals['_ASSEMBLERESPONSE']._serialized_start=143
  _globals['_ASSEMBLERESPONSE']._serialized_end=216
  _globals['_BATCHREQUEST']._serialized_start=218
  _globals['_BATCHREQUEST']._serialized_end=301
  _globals['_BATCHRESPONSE']._serialized_start=303
  _globals['_BATCHRESPONSE']._serialized_end=366
  _globals['_HEALTHREQUEST']._serialized_start=368
  _globals['_HEALTHREQUEST']._serialized_end=383
  _globals['_HEALTHRESPONSE']._serialized_start=385
  _globals['_HEALTHRESPONSE']._serialized_end=417
  _globals['_METRICSREQUEST']._serialized_start=419
  _globals['_METRICSREQUEST']._serialized_end=435
  _globals['_METRICSRESPONSE']._serialized_start=437
  _globals['_METRICSRESPONSE']._serialized_end=560
  _globals['_METRICSRESPONSE_METRICSENTRY']._serialized_start=514
  _globals['_METRICSRESPONSE_METRICSENTRY']._serialized_end=560
  _globals['_DOCUMENTASSEMBLER']._serialized_start=563
  _globals['_DOCUMENTASSEMBLER']._serialized_end=864
# @@protoc_insertion_point(module_scope)
