# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import assembler_pb2 as src_dot_proto_dot_assembler__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/proto/assembler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentAssemblerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssembleDocument = channel.unary_unary(
                '/assembler.DocumentAssembler/AssembleDocument',
                request_serializer=src_dot_proto_dot_assembler__pb2.AssembleRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_assembler__pb2.AssembleResponse.FromString,
                _registered_method=True)
        self.BatchAssemble = channel.unary_unary(
                '/assembler.DocumentAssembler/BatchAssemble',
                request_serializer=src_dot_proto_dot_assembler__pb2.BatchRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_assembler__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/assembler.DocumentAssembler/HealthCheck',
                request_serializer=src_dot_proto_dot_assembler__pb2.HealthRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_assembler__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/assembler.DocumentAssembler/GetMetrics',
                request_serializer=src_dot_proto_dot_assembler__pb2.MetricsRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_assembler__pb2.MetricsResponse.FromString,
                _registered_method=True)


class DocumentAssemblerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AssembleDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchAssemble(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentAssemblerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssembleDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.AssembleDocument,
                    request_deserializer=src_dot_proto_dot_assembler__pb2.AssembleRequest.FromString,
                    response_serializer=src_dot_proto_dot_assembler__pb2.AssembleResponse.SerializeToString,
            ),
            'BatchAssemble': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchAssemble,
                    request_deserializer=src_dot_proto_dot_assembler__pb2.BatchRequest.FromString,
                    response_serializer=src_dot_proto_dot_assembler__pb2.BatchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=src_dot_proto_dot_assembler__pb2.HealthRequest.FromString,
                    response_serializer=src_dot_proto_dot_assembler__pb2.HealthResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=src_dot_proto_dot_assembler__pb2.MetricsRequest.FromString,
                    response_serializer=src_dot_proto_dot_assembler__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assembler.DocumentAssembler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('assembler.DocumentAssembler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentAssembler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AssembleDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assembler.DocumentAssembler/AssembleDocument',
            src_dot_proto_dot_assembler__pb2.AssembleRequest.SerializeToString,
            src_dot_proto_dot_assembler__pb2.AssembleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchAssemble(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assembler.DocumentAssembler/BatchAssemble',
            src_dot_proto_dot_assembler__pb2.BatchRequest.SerializeToString,
            src_dot_proto_dot_assembler__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assembler.DocumentAssembler/HealthCheck',
            src_dot_proto_dot_assembler__pb2.HealthRequest.SerializeToString,
            src_dot_proto_dot_assembler__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assembler.DocumentAssembler/GetMetrics',
            src_dot_proto_dot_assembler__pb2.MetricsRequest.SerializeToString,
            src_dot_proto_dot_assembler__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
